# Flight Delay Analysis

## Attributes Info.

1. YEAR - Year of the Flight Trip
2. MONTH - Month of the Flight Trip
3. DAY - Day of the Flight Trip
4. DAY_OF_WEEK - Day of week of the Flight Trip
5. AIRLINE - Airline Identifier
6. FLIGHT_NUMBER - Flight Identifier
7. TAIL_NUMBER - Aircraft Identifier
8. ORIGIN_AIRPORT - Starting Airport
9. DESTINATION_AIRPORT - Destination Airport
10. SCHEDULED_DEPARTURE - Planned Departure Time
11. DEPARTURE_TIME - [ WHEEL_OFF - TAXI_OUT ]
12. DEPARTURE_DELAY - Total Delay on Departure
13. TAXI_OUT - The time duration elapsed between departure from the origin airport gate and wheels off
14. WHEELS_OFF - The time point that the aircraft's wheels leave the ground
15. SCHEDULED_TIME - Planned time amount needed for the flight trip
16. ELAPSED_TIME - [ AIR_TIME+TAXI_IN+TAXI_OUT ]
17. AIR_TIME - The time duration between wheels_off and wheels_on time
18. DISTANCE - Distance between two airports
19. WHEELS_ON - The time point that the aircraft's wheels touch on the ground
20. TAXI_IN - The time duration elapsed between wheels-on and gate arrival at the destination airport
21. SCHEDULED_ARRIVAL - Planned arrival time
22. ARRIVAL_TIME - [ WHEELS_ON+TAXI_IN ]
23. ARRIVAL_DELAY - [ ARRIVAL_TIME-SCHEDULED_ARRIVAL ]
24. DIVERTED - Aircraft landed on airport that out of schedule
25. CANCELLED - Flight Cancelled (1 = cancelled)
26. CANCELLATION_REASON - Reason for Cancellation of flight: A - Airline/Carrier; B - Weather; C - National Air System; D - Security
27. AIR_SYSTEM_DELAY - Delay caused by air system
28. SECURITY_DELAY - Delay caused by security
29. AIRLINE_DELAY - Delay caused by the airline
30. LATE_AIRCRAFT_DELAY - Delay caused by aircraft
31. WEATHER_DELAY - Delay caused by weather

In [2]:
import numpy as numpy
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
data = pd.read_csv('flights.csv')
data.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
YEAR                   int64
MONTH                  int64
DAY                    int64
DAY_OF_WEEK            int64
AIRLINE                object
FLIGHT_NUMBER          int64
TAIL_NUMBER            object
ORIGIN_AIRPORT         object
DESTINATION_AIRPORT    object
SCHEDULED_DEPARTURE    int64
DEPARTURE_TIME         float64
DEPARTURE_DELAY        float64
TAXI_OUT               float64
WHEELS_OFF             float64
SCHEDULED_TIME         float64
ELAPSED_TIME           float64
AIR_TIME               float64
DISTANCE               int64
WHEELS_ON              float64
TAXI_IN                float64
SCHEDULED_ARRIVAL      int64
ARRIVAL_TIME           float64
ARRIVAL_DELAY          float64
DIVERTED               int64
CANCELLED              int64
CANCELLATION_REASON    object
AIR_SYSTEM_DELAY       float64
SECURITY_DELAY         float64
AIRLINE_DELAY          float64
LATE_AIRCRAFT_DELAY    float64
WEATHER_DELAY          float64
dtypes: float64(16), int64(10), object(5)
memory usage: 1.3+ GB